### ISSUE TITLE
0.22.0 no longer working

### ISSUE THREAD

**Issue by gurugeek** [loopwerk/Saga#16]
I have been using Saga 0.22.0 for a while but now is no longer working 

I get this error 
    ^
```
/Users/gurugeek/..../.build/checkouts/Swim/Sources/Swim/Visitor.swift:98:5: error: missing return in instance method expected to return 'Self.Result'
    }
```

I couldn't figure out how to run 1.0.0 and I am always not sure on upgrading with breaking changes but it seems like 0.22.0 is no longer working even from my forker repository. I am probably doing something wrong so I welcome your input!

**Comment by gurugeek** [comment]
some further info: also 1.0.0 seems to fail with swift 5.6 but works fine on swift 5.5

**Comment by kevinrenskers** [comment]
I've reported this to the dependency with the actual problem: https://github.com/robb/Swim/issues/39.

I'm afraid this isn't something I can fix in Saga.

**Comment by kevinrenskers** [comment]
If you update the Swim (HTML) package to 0.4.0, everything will work again.
